import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Mavzu1 extends StatelessWidget{
@override
Widget build(BuildContext context) {
  return MaterialApp(
    title: "route",
    home: Scaffold(
      appBar: AppBar(title: Center(child: Text('Linguistic and stylistic analysis of the text'),),),
      body:
          SingleChildScrollView(child: Text("""Linguistic and stylistic analysis of a literary text
- a detailed and thorough analysis of the role and functions of language tools at different levels in the organization and expression of the ideological and thematic content of the work.
       The beginning of the formation of theoretical bases of the linguistic analysis of literary text  was inherent in the work of the famous Russian linguist L. V. Scherba "Experience linguistic interpretation of the poems". The scientist pointed to the failure information analyzing artistic works only to the different historical-literary or historical-cultural constructions 
      At the same time, a separate literary text  was isolated by the researcher from the General context of literature and considered as an immanent phenomenon.
V. V. Vinogradov in his work "on the language of fiction" substantiates the idea that the language of literary text can also be considered by the "project" method, i.e. as an element of the General literary and linguistic context. In this regard, today there are two types of analysis of the literary text : immanent and project.
      A special growth in the interest of linguists to the problems of L. A. H. T. has been noted since the late 60s of the twentieth century, and in the early 70s, L. A. H. T. is introduced into the program of pedagogical institutes as a special discipline. It was in the 70s that the domestic theory of L. A. H. T. was developed (see the works of L. G. Barlas, V. p. Vompersky, A. I. Gorshkov, S. G. Ilenko, E. V. Kapatsinskaya, V. I. Kodukhov, N. A. Kupina, A. N. Kozhin, L. Yu.Maksimov, L. A. Novikov, V. V. Odintsovo, L. F. Tarasov, N. M. Shansky, and others).     Gradually increasing trend towards the integrated study of literary works, when linguistic analysis 1) is treated as an integral part of the study of the text; 2) covers units of all language levels; 3) is subject to extralinguistic bases of text-production; 4) is combined with related disciplines (history, cultural studies, literature, psychology, communication science, etc.) for the purpose of interpreting linguistic characteristics; 5) increasingly extends to the level of analysis whole text (the entire piece).
           It is a complex analysis of literary text  that allowed us to see that the interaction of language units within the text is not random, but purposeful: the language structure (linguistic pattern) of the work is always deeply thought out by the author in terms of the most complete and effective (as well as effective) implementation of the aesthetic concept in it.
       In contrast to literary analysis (which is the study of figurative and ideological plans of the text, the definition of the features of its interaction with cultural-historical and conceptual creativity of the author contexts, the study of literary text  as a fact of history of social thought and social struggle, etc.) the subject of  linguistic analysis of literary text  serves as the linguistic organization of the text, namely connections and relations of units of different levels, in unity expressing a particular line aesthetic concept of the work.
       Therefore, the material of linguistic analysis of literary text  turns out to be: 1) archaisms and historicisms; 2) incomprehensible facts of poetic symbolism; 3) dialectics, professionalism, argotisms, jargonisms and terms that are unfamiliar or unfamiliar to the reader; 4) features of the writer's word usage: individual author's language innovations; 5) keywords; 6) tropes; 7) features of syntax; 8) originality of composition; 9) specifics of the use and coupling of neutral and stylistically significant (expressive) language elements and structures; 10) features of the language organization of the subtext; 11) features of the choice and organization of language material in its particulars and integrity – speech consistency; 12) the relationship between the language and semantic levels of the text in terms of the completeness of the author's concept, etc.
         With regard to the latter type of material of linguistic analysis, it should be said that the question of how a writer uses language when expressing a certain artistic content belongs rather to the field of stylistic analysis. However, the study of the aesthetic function of language already presupposes a complementary unity of linguistic and stylistic analyses, "forming a complex lingua stylistic analysis of how and how the unique originality of a literary work is created".
      This means that the main task of  linguistic analysis of literary text is to study the language tools of different levels in the system of a certain HT from the point of view of their compliance with the author's idea and his individual writing style. At the same time, the unity of form and content is the initial methodological principle of the modern  linguistic analysis of literary text 
     Therefore, the explanation of the structural features of the text must be correlated with meaningful concepts and categories, such as the theme, idea, author's idea, artistic and imaginative system.
      In accordance with this, the main goal of linguistic analysis of literary text is to consider literary text as an organized system of language means that reflects a certain ideological, thematic, figurative and aesthetic content of the text in their   general and special features. 
     In this case, the set of language means of the writer should be considered, according to A. I. Gorshkov, not as a "language", i.e. not as a mechanical articulation in the text of linguistic forms and techniques ( language material), but as a "style", i.e. "language reality", the very functioning of the language, based on which specific cases of use, use of elements of the national language system are identified.
        L. A. Novikov distinguishes several types of linguistic analysis: 1) linguistic analysis-disclosure of the meaning of various elements of the language in order to fully and clearly understand the text. This analysis can be a) basic practical, shared employees "clarification" of the text (e.g., explanation of obsolete words and forms of language), and b) linguistic, based on data from linguistic theory, the facts of the language system and its history; 2) stylistic analysis, study of figurative means of the text as a) in different styles and genres and b) copyright; 3) literary analysis-the study of literary text as a product of national culture, social thought, works of verbal art (ie, the study of the relationship of  literary text with the era, its place in the literary process and creativity of the writer, issues, ideological content, images, composition, plot, language, etc.). in this case, linguistic analysis of literary text  is based, according to the scientist, on a number of basic provisions that form its principles, including: 
       1) consideration of literary text in a threefold aspect: "ideological content-image-language".  Intermediate position of the device. the image in this series makes the first "center" of the ideological and aesthetic content and a certain form of its linguistic expression, which gives the image individuality and uniqueness. "The image turns out to be addressed by its different sides simultaneously to the ideological and social content of the literary text, being included in the General system of images ("literary image"), and to the language, the language. material ("verbal image"). It represents a kind of dialectical unity of these different principles"; 
        2) the concrete historical approach to the interpretation of the text based on the cultural-historical review, providing a more complete and deep understanding of literary text in the context of the period of public life, to which belongs the studied text;
         3) the distinction in the text of the normative facts inherent in modern usage, and various deviations from the norm, facts;
        4) understanding of poetic language as a special form of aesthetic understanding of reality, as an active means of creating art. generalizations; 
         5) the active role of the reader (interpreter) of the text;
          6) the unity of various principles of interpretation of literary text, the scheme of which varies depending on the features of the text and the goals of its analysis.
"""),
          ), backgroundColor: Colors.lightBlueAccent

    )
  );
  }}