import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Mavzu2 extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "route",
        home: Scaffold(
          appBar: AppBar(title: Center(child: Text('The interpretation of the literary texts'),),),
          body:
          SingleChildScrollView(child: Text("""Questions to be discussed:
Literature as Subject Matter for Writing
Criteria for Selecting Suitable Literary Texts
The peculiar features of the literary text
Key words: Criteria, suitable Literary Texts, features of the literary text, interpretation, writing.
There are many good reasons for using literature in the classroom. Here are a few:
Literature is authentic material. It is good to expose learners to this source of unmodified language in the classroom because they skills they acquire in dealing with difficult or unknown language can be used outside the class.
Literature encourages interaction. Literary texts are often rich is multiple layers of meaning, and can be effectively mined for discussions and sharing feelings or opinions.
Literature expands language awareness. Asking learners to examine sophisticated or non standard examples of language (which can occur in literary texts) makes them more aware of the norms of language use.
Literature educates the whole person. By examining values in literary texts, teachers encourage learners to develop attitudes towards them. These values and attitudes relate to the world outside the classroom.
Literature is motivating. Literature holds high status in many cultures and countries. For this reason, students can feel a real sense of achievement at understanding a piece of highly respected literature. Also, literature is often more interesting than the texts found in course books.
Literary texts provide opportunities for multi-sensorial classroom experiences and can appeal to learners with different learning styles. Texts can be supplemented by audio-texts, music CDs, film clips, podcasts, all of which enhance even further the richness of the sensory input that students receive.
Literary texts offer a rich source of linguistic input and can help learners to practice the four skills - speaking, listening, reading and writing - in addition to exemplifying grammatical structures and presenting new vocabulary.
Literature can help learners to develop their understanding of other cultures, awareness of ‘difference' and to develop tolerance and understanding. At the same time literary texts can deal with universal themes such as love, war and loss that are not always covered in the sanitized world of course books. Literary texts are representational rather than referential.
    Referential language communicates at only one level and tends to be informational. The representational language of literary texts involves the learners and engages their emotions, as well as their cognitive faculties .Literary works help learners to use their imagination, enhance their empathy for others and lead them to develop their own creativity. They also give students the chance to learn about literary devices that occur in other genres e.g. advertising.
      Literature lessons can lead to public displays of student output through posters of student creations e.g. poems, stories or through performances of plays. So for a variety of linguistic, cultural and personal growth reasons, literary texts can be more motivating than the referential ones often used in classrooms.
Criteria for Selecting Suitable Literary Texts
When selecting the literary texts to read we should take into account needs, motivation, interests, cultural background and language level of the reader. However, one major factor to take into account is whether a particular work is able to reveal the kind of personal involvement by arousing the learners’ interest and eliciting strong, positive reactions from them. Reading a literary text is more likely to have a long-term and valuable effect upon the learners’ linguistic and extra-linguistic knowledge when it is meaningful and amusing. 
Choosing books relevant to the real-life experiences, emotions, or dreams of the learner is of great importance. Language difficulty has to be considered as well. If the language of the literary work is simple, this may facilitate the comprehensibility of the literary text but is not in itself the most crucial criterion. Interest, appeal, and relevance are also prominent. Enjoyment; a fresh insight into issues felt to be related to the heart of people’s concerns; the pleasure of encountering one’s own thoughts or situations exemplified clearly in a work of art; the other, equal pleasure of noticing those same thoughts, feelings, emotions, or situations presented by a completely new perspective: all these are motives helping readers to cope with the linguistic obstacles that might be considered too great in less involving material .
Literature and the Teaching of Language Skills
      Literature plays an important role in teaching four basic language skills like reading, writing, listening and speaking. However, when using literature in the language classroom, skills should never be taught in isolation but in an integrated way. 
Literature as Subject Matter for Writing
       Finding appropriate material for their writing classes is sometimes difficult for composition teachers since writing has no subject matter of its own. One benefit of having literature as the reading content of a composition course is that the readings become the subject matter for compositions. In a composition course whose reading content is literature, students make inferences, formulate their own ideas, and look closely at a text for evidence to support generalizations. Thus, they learn how to think creatively, freely and critically. Such training helps them in other courses which require logical reasoning, independent thinking, and careful analysis of the text. There are mainly two kinds of writing based on literature as subject matter: writing “on or about” literature, and writing “out of ” literature. These categories are suitable and useful for ESL / EFL 
 Writing “On or About” Literature
       Writing “on or about literature” comprises the traditional assignments - written responses to questions, paragraph writing, in-class essays, and take-home compositions - in which students analyze the work or in which they speculate on literary devices and style. Writing “on or about” can occur before students begin to read a work. The teacher generally discusses its theme or an issue it raises, and the students write about it with reference to their own life experience. This helps interest them in the work and makes them ready for reading and writing about it. Most writing assignments done during as well as after the reading, however, derive from class discussion. They take many forms, such as questions to be answered, assertions to be debated, or topics to be expanded, discussion groups to be established.
 Writing “Out of” Literature
        Writing “out of” literature means making use of a literary work as a springboard for composition - creative assignments developed around plot, characters, setting, theme, and figurative language. There are many forms of writing out of literature, such as Adding to the Work, Changing the Work, Drama-Inspired Writing and A Letter Addressed to Another Character, etc. Adding to the Work: This comprises writing imaginary episodes or sequels, or, in the case of drama, “filling in” scenes for off-stage actions that are only referred to in the dialog. Changing the Work: Students can make up their own endings by comparing the author’s ending to their own. Short stories can be rewritten in whole or in part from the point of view of a character versus a third person narrator or of a different character. Drama-Inspired Writing: It is possible to derive drama-inspired writing activities from plays, short stories, novels, and sometimes poetry. The student steps into the consciousness of a character and writes about that character’s attitudes and feelings. A Letter Addressed to Another Character: The student can write a letter to one of the characters, in which he / she gives the character personal advice about how to overcome a particular problem or situation. 
 Literature, Speaking, and Listening
      The study of literature in a language class, though being mainly associated with reading and writing, can play an equally meaningful role in teaching both speaking and listening. Oral reading, dramatization, improvisation, role-playing, pantomiming, reenactment, discussion, and group activities may center on a work of literature. Oral Reading Language teachers can make listening comprehension and pronunciation interesting, motivating and contextualized at the upper levels, playing a recording or video of a literary work, or reading literature aloud themselves. Having students read literature aloud contributes to developing speaking as well as listening ability. Moreover, it also leads to improving pronunciation. Pronunciation may be the focus before, during, and / or after the reading. 
The peculiar features of the literary text
     The nature of the literary text has always been one of the central concerns of stylistics. Very important observations regarding this issue were made by famous philologists.  The text of fiction as a specific type o f communication characterized by the primary communicative activity of the author and the secondary communicative activity o f the reader, has many  peculiar features.
First and foremost the fictional text reflects an imaginary world not associated with the practical activity o f communicants, and therefore it is certainly devoid of the facto logical accuracy.
     In this respect it is expedient to make reference to the principle of “constructiveness” suggested by T.A. Van Dick with regard to literary communication. This principle postulates that the author’s intention in the fictional text is by no means “practical” communication, but the construction o f “possible”, “imaginary” worlds for the reader.
      A distinguishing feature o f the literary text is its aesthetic function. The aesthetic function presupposes a certain impact on the reader called forth both by the beauty o f a linguistic form and the conceptual significance o f its content. The aesthetic information is aimed at arousing aesthetic feelings, i.e. the feelings o f pleasure and beauty on the part o f the reader.
 Aesthetics of the text is closely interlinked with the categories of imagery, evaluation, emotiveness.
     A significant property o f the literary text is its anthropocentric character. The principle of   anthropocentrism is a key problem of modem linguistics. That means that the study of language is closely allied to a human, his activity and culture. The ideas of anthropocentrism were laid up and developed in the works by V. Humboldt, A.A. Potebnya, E. Benvenist, E. Sapir, and many others. At present the anthropocentric paradigm is the core of modem linguistics, and it has given rise to such trends as communicative linguistics, cognitive linguistics, text linguistics, linguo-pragmatics, etc. 
   The study of the literary text from the anthropocentric perspective presupposes the investigation of the linguistic personality o f the author (the author’s image) and that of a character.
      One major peculiarity o f the literary text is its complex multidimensional, multilayered structure. There are different approaches to the problem of the literary text structure. Some researchers differentiate the surface layer and the deep layer. The surface layer is a verbal layer, the linguistic form of shaping the content. The verbal layer in its turn falls into phonetic, morphological, lexical and syntactical layers. 
        The deep layer o f the text is its conceptual information including the author’s purport and pragmatic intentions. The deep layer reflects the author’s outlook, his individual world picture, aesthetic views and moral values. There are close and diverse relationships between the deep and surface layers. On the one hand, it is the deep layer that dictates the linguistic form o f the literary text, on the other - the surface layer exerts some influence on the deep layer generating new conceptual senses.
M.P. Brandes suggests such levels as compositional, emotive, psychological. Z.L. Khovanskaya speaks of a three-level structure: aesthetic, compositional and linguistic. 
Some scholars outline the pragmatic level of the text. Pragmatics of the literary text is understood as its ability to arouse an aesthetic effect predetermined by the author’s intention, his communicative strategies and aesthetic views. The pragmatic level is often mixed with the stylistic one.                          
        In our opinion, the notion of text pragmatics is concept as a unit of conceptual information, a “quantum” of knowledge and the conceptual text structure or concepto-sphere reflecting the formation and interaction o f literary concepts within the framework of the whole text.
So, in spite of different approaches to the problem o f the literary text structure, all scholars agree on the following:
the literary text is characterized by a complex, multilevel, multidimensional structure;
the levels of the literary text structure are bound together by the relationships o f interdependency interconditionality and mutually complementary interaction;
the essence and specificity o f each text layer lie in the correlation of both linguistic and extra-linguistic factors.
     The survey o f the linguistic literature and our own observations give grounds for the differentiation o f the following levels (codes) in the text structure:
the informative level subdivided from the linguistic point of view into phonetic, morphological, lexical, and syntactical, from extra-linguistic - into denotative, thematic and compositional sublevels. The denotative sublevel explicates the objects o f the described in the text reality, their relationships, coordination and subordination. The thematic level embraces a range o f vital problems and life experiences shown through the author’s individual perception. The main theme is subdivided into microthemes and subthemes which being bound together reflect the realities o f the surrounding world and its creative comprehension;
the compositional level deals with a complex organization o f the text the components o f which are arranged according to a definite system and in a special succession. Traditionally the compositional structure of the literary text consists o f the following parts: title — exposition - initial collision — development o f the plot -culmination — denouement — end. However in every concrete case this compositional scheme varies: some parts can be omitted or rearranged. There are different types o f the compositional structure: prospective, retrospective, linear, parallel, multidimensional).
the semantic level is concerned with the meanings and contextual senses o f text units, their syntagmatic and paradigmatic parameters, connotative and associative links. Most important in this respect is the role o f lexical units, which make the basis for the semantic development o f the text and its associative structure;
 the stylistic level includes many aspects o f the text style dealing with a) stylistic categories such as emotiveness, imagery, implicitness, modality, intertextuality and linguistic forms o f their representation; b) expressive means and stylistic devices, their functions and pragmatic effects; c) the peculiar features of an idiostyle;
the pragmatic level involves: a) pragmatic factors and linguistic means o f impact on the reader, which secure his understanding, arouse his interest and emotions and involve him in the author’s creative activity, c) the parameters of linguistic personality presented in the author’s and the character’s images;
the cultural level reflects individual and national cultural values, knowledge about historical, political, social, religious notions and events. The most important role is assigned to the language units conveying cultural information presented by a great variety of linguistic forms: words, word combinations, phraseological units, text fragments;
the conceptual (cognitive) level is closely knit with an aesthetic function of the text and represents an individual conceptual world picture reflecting the author’s aesthetic credo, his purport and world perception. From the linguistic point of view the analysis o f this level aims to describe relationships between textual features and cognitive processes, linguistic choices and cognitive structures.
    The analysis of the literary text peculiarities wouldn’t be complete if we did not touch upon the problem of text interpretation. Interpretation is a purposeful cognitive activity aimed to disclose a deep-lying conceptual content of the text. Them procedure of interpretation consists in constructing and verifying: hypotheses about conceptual information of the literary text, the inner substance o f things and phenomena. A pervasive feature o f the literary text is a multitude of its interpretation which is accounted for by such properties as implicitness, ambiguity, imaginative and connotative qualities. It should be stressed, however, that the multitude of interpretation is by no means of a subjective and arbitrary character. There is a certain objective invariant of interpretation, which is substantiated by the text itself. 
       Therefore the analysis of the verbal layer of the text, its basic linguistic signals, markers to be guided by in the process of interpretation appear to be o f prime importance. To such signals we refer the language means put in the position of salience, focus, foregrounding. They are: key words, recurrence, stylistic devices and their convergence, poetic details and many others.
       Proceeding from the fact that the literary text is a complex multilayered structure, we have to acknowledge the necessity of its complex, multilateral and multistage analysis and interpretation. In other words, the study o f the literary text requires a holistic (derived from “whole”) approach. It means that the text should be considered in the integrity of its linguistic and extra-linguistic factors, the surface and deep layers of the text, its stylistic, communicative, pragmatic, cultural, cognitive and aesthetic aspects.
In summing up, the following conclusions can be made:
the literary text is a specific type of communication characterized by many a peculiar feature: a) an anthropocentric character; b) the construction of an imaginary world; c) aesthetic values and cultural entity;
the literary text is characterized by a complex structure comprising the hierarchy of informative, semantic, stylistic, pragmatic, cultural, cognitive levels, each of them based on the correlation of linguistic and extra-linguistic factors.
"""),),

        )
    );
  }}