import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Mavzu5 extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "route",
        home: Scaffold(
          appBar: AppBar(title: Center(child: Text('The usage of some stylistic devices in belles-lettres style'),),),
          body:
          SingleChildScrollView(child: Text("""Questions to be discussed:
Compound epithets
Oxymoron
Usage of Antonomasia, Hyperbole
Figurative periphrasis, Allusion
Key words: Compound epithets, Antonomasia, Allusion, Oxymoron, Hyperbole, methaphor
Handouts 1. Fishbone
Compound epithets stand very close to compound adjectives: weak- minded ideas, a cast-iron opinion, a shamed –looking dog, a carefully thought out curses, fairy- like work. 
Phrase (or sentence) epithets: a life-and death struggle: her mother ran up, and came into the bed room with a worried-end-of-the-world frown on her face (E.O’brien); The structural type of the reversed epithet consists of two nouns connected by an “of phrase”: a claw of fear, a day of happiness. These are called metaphorical epithets. 
Oxymoron is the use of an epithet (or an attributive phrase) that is contradictory to the noun it modifies. Eg.: Chopin’s beautiful sorrow, a generous miser, busy idleness, a beautifully ugly face.
An oxymoron is used to give a figurative characterization of a notion to reveal its inner complicated nature. It may serve to  denote a temporary feature of a notion.
Eg.:It was with an almost cruel joy. Suddenly she felt the need to speak. The wordy silence troubled her; it was a relief to be on board and no longer alone together (D.Garnett).
The stylistic effect is based on the fact that the denotational meaning of the attribute is not entirely lost. If it had been lost the word combination would resemble those attributes with only emotional meaning such as: It’s awfully nice of you, I’m terribly glad. 
Usage of Antonomasia. This SD is based on the immediate interplay between logical and nominal meanings of a word which is realized in the text. The realization of only one meaning does not give an SD.
Here are some illustrations of antonomasia  widely used in emotive prose and drama: Mclash, one who strikes violently (compare with the verb to lash). Mr.Micphail (compare with the verb to fail), Vu. Pinchwife, one who hurts his wife by pinching; Mr.Sparkish, dandy, a man who pays too much care to his clothes and personal appearance (compare with the adjective sparkle). Sir fidget, a person who moves about restlessly, shows signs of impatience. The same refers to Mcfission, Frincle.
Sometimes capital letters are the only marks of the use of antonomasia and the implication which such antonomasia carries in the text. Eg. : lord Nobody, Dr.Goodfeel. traditionally proper names are built according to certain morphological patterns: noun + suffixes: -son, -er, -ard etc. eg.: Jonson, Morrison, Chester, Herbert, Howard, Bernard, etc. Alongside with antonomasia we single out token or telltale names. Eg.:Miss careless, Mr Desert, Sir Pattern. In such names the leading characteristic feature of a person or some event is marked or mentioned.
Antonomasia is associated with other SDs. For example, it is often used together with epithets. Speaking about epithets we have underlined that it denotes certain (special) qualities of a person (p. 5). Many nicknames of historical or public characters are based on the use of such characterization. Eg: The Iron Duke (the first Duke of Wellington), Old Hickory (Andrew Jackson, the seventh President of the USA), the Iron Lady (M. Thacher, the former Prime Minister of Great Britain) etc.
Another type of antonomasia is metonymic antonomasia which is based on the relation of contiguity. A product can be named after the inventor, manufacturer or after the place where it is produced: Chanel, Nina Ricci ( french scent), Bordeaux (white or red wine from the Bordeaux region of France). 
We distinguish metaphoric antonomasia which is usually considered to be a cliche. Eg.: He is a regular Sherlock Holms, may be said about an observant person; Romeo and Juliet, young people who love each other. The significance of antonomasia in belles-lettres style should not be neglected because it helps to reveal the hidden meaning of the story of narration. For example, in W. Shakespeare’s “Hamlet” at the end of the play the Prince of Norway, Fortenbrass appeares on the stage. The meaning of his name is significant in interpreting Shakespear’s conception. It consists of two words: “fort” and “bras”. The first word means “a building specially strengthened for military defense”, the second word “brass” is a French word and denotes a “hand”. The implication is that people need a strong and brave ruler (King) in this country.
Usage of Similes in Belles letters style. Sometimes for a special reason one of the features of the thing is made the most essential, describes some detail and intensifies it. Such SDs as simile, periphrasis, euphemism and hyperbole are included into this group.
Simile reveals the most essential features of an object (or person) and draws a comparison between two different things.
Such formal elements as: like, as, such as, as if, seem etc. introduce similes and comparison. We must not confuse ordinary comparison and simile as an SD. Comparison implies estimation of two objects which belong to one class of objects. Its purpose is to show the features which bring these objects together: If he is like his mother he must be a good-looking boy, two human beings are compared.
The nature of simile is to compare two (or several) objects which belong to different class 'of things. Simile finds one or several features which are common to the objects compared: The sun was as red as ripe new blood (J. Steinbeck).
If we compare a simile with a metaphor we can see that a metaphor is also based on the similarity of two ideas, but in simile both ideas are denoted by words used in their direct meaning: Della’s beautiful hair fell about her ripping and shining like a cascade of brown water ... (0. Henry). In a metaphor an idea is expressed by a word used in a figurative meaning: Down rippled the brown cascade of her hair. (Down fell in ripples her hair). In the first sentence the word “cascade” has retained its direct meaning (waterful) in the second example it is used in a figurative meaning as a metaphor (wave-like fall of the hair).
The stylistic function of simile may be different: 
1) imaginative characterization of a phenomenon.
2) to produce a humorous effect by its unexpectedness: A nice old man, hairless as a boiled onion.
Usage of Periphrasis in Belles letters style. Periphrasis is the nomination of an object or action through exhibiting certain features of this object or action. Such periphrasis is based on one of the original features of the object: The sun was beginning to yawn and edge towards his bed, behind the far mountains (S. Maugham), the sun was setting. She wondered a little to and fro, perhaps clumsily, but still with marked success, maintaining her balance on those two tiny supports (A. Bennett), standing on her little feet.
Periphrasis are divided into two groups: logical and figurative. In the first group of periphrasis the logical notion prevailes while in the second group — the figurative notion is leading and periphrasis is based on some image. The logical periphrasis constitutes the essence of traditional dictionary periphrasis: to turn over a new leaf (make a new, a better start), one's better half (one’s wife), to tie the knot (to marry); the House of God (the church or chapel); to enter the House (to become an MP) etc. All these word combinations are synonyms by nature and have become phraseological units. Many of such word combinations are used in the language of mass media. 
Figurative periphrasis is often based on the use of a metaphor or metonymy: Five weeks of perfect liberty ... would have prepared her for the day of bells (E. Meredith) (for the day of wedding). He jumped to his feet, rattled his throat, planted firmness on his brows and mouth ... that his blood might be lively at the throne of understanding (E. Meredith) (his brains). Everybody would, smile when such expressions are used in everyday spеech: “A period of unfavourable weather set in” instead of "It rained every day”, “He showed satisfaction as he took possesion of his well-earned reward” instead of “He grinned as he pocketed the coin". One of the stylistic functions of periphrasis is to produce a satirical or humorous effect, sarcastic description: “Come on”, said Miss Handforth, “has the cat got your tongue?” (I. Murdoch) (Can you speak?); to be snatched up to the skies (to die). It may create elevated style. Eg.: — And what do you do all day? — I imbibe nourishment in my room, replied the Baron. (K. Mansfield).
In some cases periphrasis is regarded as a demerit and should have no place in good precise writing. It is generally called circumlocution.
Euphemism is a periphrasis which is used to rename an unpleasant word or expression. Eg. death: the journey’s end, sleep; to die; to cross the bar; to join the majority. Usually euphemisms are defined as words or phrases which produce some mild effect. Instead of saying "to lie” people usually use such expressions as: to tell stories, to possess a vivid imagination.
We distinguish the following groups of euphemisms: religious, moral, medical, politicaletc. The political euphemisms always delude public opinion, distort the political events. Capitalists are called “free enterprises: uneployment is called "building up of labour reserves”, “dismissal of (discharge) of workers”, “reorganization of the enterprise".
One and the same word may be periphrased by different euphemisms in different speech situations. For example, the word “liar" in private conversation may have the following euphemisms: untruther, story-teller, fabulish; in press: reckless disregarder for truth, dissimulator, misleader, falsier, fabricator etc.
In emotive prose euphemisms are usually expressed by metonymy, metaphors or periphrases. One of the stylistic functions of euphemisms — is to' produce a humorous effect or to distort the truth, to make the statement milder. Eg.: intoxication — drunkenness, perspiration — sweat etc.
Usage of Hyperbole in Belles letters style. Hyperbole as an SD must be distinguished from exaggeration, very exaggeration cannot be regarded as an SD. For example, the following expressions: Haven’t seen you for ages; Гm dying to see it
Hyperbole may be expressed in a periphrastic descriptive way: What I suffer in that way no tongue can tell (J. K. Jerome). “No tongue can tell” means “it is very difficult to express by means of the language”. In this case hyperbole is based on metonomy (tongue). Hyperbole may be used in combination with other SD, hyperbolic similes: His mind began to move like lightning. She was as graceful as a meridian of longitude (S. Leacock); hyperbolic metaphors: Gradually he was becoming acclimatized to the strange town, primitive and isolated entombed by the mountains (A. Cronin). Hyperbole may be found in repetition: I’d have been out there days ago — days ago (S. Leacock).
           Usage of certain set expressions in Belles letters style. 
Every language has a lot of word combinations, where the meaning of the whole dominates the meanings of the parts. Sometimes we say — the meaning of the whole doesn’t correspond to the meaning of the parts. These word combinations arc called set expressions of phraseological word combinations, language idioms. One of their typical features is their stability. The components of idioms have fixed place in the utterance and semantic unity. Set expressions are the part of the language and they are used as ready-made units.
Among such ready-made units we must distinguish several types. The first is the clicheIt is an expression that has become trite, hackneyed and stereotyped due to the constant reiteration. But is it a fault that the phrase was in common use? Of course not. Clich6s denote word combinations which have lost their freshness. Here are some examples: it goes without saying, so much, well begun is half done, better late than never etc.
If one word inevitably invites another, if you read half of the sentence and know pretty certainly what the other half is, you have cliches. (R. Altick). 
The second type of set expressions are proverbs and sayings. Proverbs are brief statements which show in a condenced form the accumulated life experience of the society. They are usually expressive and have generalized meaning. Many of them are based on the use of  rhyme, alliteration. Eg.; pass in a lion’s skin; first come, first served; good as gold. Proverbs are always brief because of the omission of conjunctions. Eg.:better late than never, out of sight, out of mind.
Proverbs may be handled not in their fixed form (traditional model) but with some modifications. Eg.: Marriages are made in Heaven — a fixed or traditional form; Divorces are made in Heaven
a modified form; Look years younger — traditional form; Look weeks younger — a modified form; If war breaks out — a traditional form; If peace breaks out — a modified form.
Epigrams are very close to proverbs. The difference between them lies in the fact that epigrams are created by individuals, famous writers, poets, scientists, philosophers whom we know, while proverbs belong to the people. The typical features of proverbs and sayings form the background of epigrams. We may say that proverbs and sayings are used as EM of the language while epigrams constitute the SD. Epigrams are literary expressions while proverbs are utterances of the folk language. Epigrams like proverbs hold the unity of the idea they express. Let’s see the following examples: A clear consience makes a man very happy. (I. Murdoch) Some books are to be tasted, others to be swallowed, and some few to be chewed and digested (F. Bacon).
Epigrams must meet all the necessary requirements of the proverbs: they must be brief, generalizing, witty. Eg.: Sweet is revenge, especially to women (G. Byron); A little learning is a dangerous thing (A. Pope); A man's best friend is his own pound note (A. Cronin); Fame is the thirst of youth (G. Byron).
Allusion is аn indirect mention of some word or utterance from some book or event. Usually the reference to the source of the historical, literary or mythological fact is not given. Sometimes allusion is the only key which is used in the text to understand the whole meaning of this text. By this allusion differs from a quotation. Let’s see the following example: “Good god”, said Demoyte. Is that all you’ve done, in the last two hours? ... at this rate you’ll be with us for years. But perhaps that’s what you want — like Penelope, never finishing her work?" (I. Murdoch.) In this case allusion is made to Homer’s “Odyssey”. Allusions may be used in different functional styles. Here is an example of allusion used in a newspaper headline: The Plains in Spain are a Bit of a Pain. It is a reference to a well-known phrase from B. Shaw’s play “Pygmalion” (Rains in Spain fall mainly in the plain). In order to get adequate information about the use of allusion in the text reader must be acquainted with the essence of this allusion, to know the source from which it was taken.
 The stylistic function of allusion is various: either to make the comparison, or to produce a humorous effect.
 """),),

        )
    );
  }}