import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Mavzu7 extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "route",
        home: Scaffold(
          appBar: AppBar(title: Center(child: Text('The Theory of Cognitive Metaphor'),),),
          body:
          SingleChildScrollView(child: Text("""  Questions to be discussed:
Metaphor is a unique phenomenon
structural metaphor
orientational metaphor
ontological metaphor
Key words: Cognitive metaphor, structural metaphor, orientational metaphor, ontological metaphor
      Metaphor is a unique phenomenon that had been studied by philosophers and philologists all along. For over 2000 years since Aristotle metaphor had been regarded as a figure o f speech based on implicit comparison, analogy. In the early eighties the emergence of the Conceptual Theory of Metaphor changed this traditional interpretation of metaphor. At present, metaphor has been looked upon as not only a stylistic device, but as a cognitive mechanism, a way of thinking and cognition.
      This framework was first proposed by G. Lacoff and M. Johnson in their revolutionary work “Metaphors We Live By”, and since then has been developed and elaborated in a number of subsequent researches (Turner, 1991; Kqvecses, 2000; Gibbs, 1994; Reddy, 1979). 
    A fundamental tenet of this theory is that metaphor operates at the level o f thinking as “our conceptual  system is largely metaphorical, and our ordinary conceptual systems, in terms o f which we both think and act, is fundamentally metaphorical in nature” (Lacoff, Johnson, 1980:3).
      In their research, Lacoff and Johnson made a penetrating systematic analysis of the metaphorical concept system drawing clear distinction between conceptual metaphor and metaphorical expressions. They assert that the focus of conceptual metaphor is in the mind, in the way we conceptualize one mental domain in terms of another, for example, understanding Time in terms of Money (e.g.  time is money, I don’t have time to give you).
Conceptual domain is understood as “relatively complex knowledge structures which relate to coherent aspects of experience” (GCL, 2007:61), or, in other words, any coherent organization of human experience.
     In terms of the cognitive approach metaphor is defined as “a cross-domain mapping in the conceptual system” (Lacoff, 1992), as “a cognitive mechanism whereby one experimental domain is partially “mapped”, i.e. projected onto a different experiental domain, so that the second domain is partially understood in terms of the first one” (Barcelona, 2000:3). A cross-domain mapping is a systematic set of correspondences that exist between constituent elements o f the “source-domain” and the “target-domain”.
      The target domain is the domain being described and the source domain is the domain in terms of which the target is described. According to Lacoff , the target-domain “Mind” is structured in terms o f the source-domain “Machine”, the target- domain “Love” is structured in terms of the source-domain “Journey”, thus establishing a conceptual metaphor “The Mind is Machine”, “Love is Journey”. Kuvecses Z. claims that the most common source-domains for metaphorical mapping include domains relating to the Human, Body, Animals, Plants, Food and Forces. The most common target-domains include such conceptual categories as Emotion, Morality, Thought, Human Being Relationship and Time. Thus, the source domain tended to be more concrete whereas the target domains are abstract and diffuse.
      So, metaphor is a basic scheme by which people conceptualize their experience and their external world.
    There are several types o f conceptual metaphors identified by George Lakoff and Mark Johnson in “Metaphors We Live By’’.
structural metaphor refers to the metaphorical and structural organization o f one concept (often an abstract one) in terms o f another (often a more concrete one). In this case, the source domains provide frameworks for the target domains  (Time is Money; Argument is War)
orientational metaphor “organizes a whole system of concepts with respect to one another” and is concerned with spatial orientations: up-down, in-out, front-back, on-off, deep-shallow, central-peripheral {Happy is Up, Sad is Down);
ontological metaphor relates to "ways of viewing events, activities, emotions, ideas, etc., as entities and substances". In other words, this is a type of metaphor in which something concrete is projected onto something abstract  {Inflation is an Entity; the Mind is an Entity).
conduit metaphor refers to communication and operates whenever the addresser inserts his mental ideas, (feelings, thoughts, etc. ) into words, phrases, sentences, etc. in his message to the addressee who then extracts them from these linguistic forms. Thus, language is viewed as a "conduit" conveying mental content between Another type o f conceptual metaphor — container metaphor. The notion of “container” appears to be very significant for the Conceptual Metaphor Theory since it reflects body-based experience, human-being relationships, orientation in time and space, etc. Container metaphor operates in the following way; one conceptual domain is supposed to be “in” another conceptual domain. As Lakoff and Johnson point out, container logic is also helpful for imagining logical schemas stemming from “inclusion”: e.g. Container A is inside Container B and Entity C is inside Container A, then Entity C is inside Container B. Moreover, container logic is probably most important in grounding how people think of their own minds (e.g. He has a great idea in his mind). We imagine memories or some information being “stored” in our minds as if our mind was a separate “container” for each memory trace or idea.
     This type of conceptual metaphor is of paramount importance for Cognitive Stylistics and the analysis of the literary text. One of the essential characteristics of conceptual metaphor in general and container metaphor in particular is its prototype character. The container metaphor is one of the most important and deeply ingrained metaphors in the human cognitive toolkit. It’s seemingly simple, but a very powerful type of metaphor.
     According to E.S. Kubryakova’s conception, the notion of “container” gives grounds for modeling one of the main principles of human cognition regarding the whole universe as a multitude objects inserted one into another. In this respect container metaphor should be looked upon as a general image- schema, embracing various types of metaphors. Thus, metaphors built on the relationships of Nature and Man belong to the type of container metaphors since Man is an inseparable part of Nature. It should be noted here that the relationships between metaphors and their linguistic forms are not direct. It means that the same conceptual metaphor can be expressed through a variety of constructions).
The observation of the linguistic media makes it possible to outline various subtypes of conceptual metaphors included into container metaphor “Human is Nature”:
    Human is Animal (animalistic type):  Two thin teeth, like those of a rat, overplay the shivered lower lip(Doyle, Playing with Fire);  Miss Chandwick wrinkled up her forehead and looked rather like a perplexed Boxer doe(A. Christie, Cat among the Pigeons);
     Human is Bird: (ornithological type):  ...his eyes were like owl’s eves, piercing, melancholy dark brown(Galsworthy);  June went along the Squire with her bird-like quickness(Galsworthy, The Man o f Property);  their eves stabbed like the eves o f an offended swan(Galsworthy, The Man of Property);
    Human is Plant (floristic type):  Jane, you look blooming. And smiling, and pretty (Bronte, Jane Eire);  Her hair clustered round her face like a dark leaves round a pale rose(Wilde, The picture  of Dorian Grey);  His cool, white, flowerlike hands, even, had a curious charm(Wilde, The picture o  Dorian Grey); 
     Human is Tree:  And Jephson, his long, tensile and dynamic body like that of a swaying birch, turning toward...(Dreiser, An  American Tragedy);
     Human is Natural Phenomenon: ...they had never seen anyone look so thunder and lightning as that little June! (Galsworthy, The Man o f Property); Your hands are like snowdrops. Mary(Cronin) 
 Human is Mineral: Mrs. Upjohn was an agreeable young woman in her late thirties, with sandv hair, freckles and unbecoming hat... (Christie, Miss Marple’s Final Cases)
   Human is Season:  The spring had got into his blood (Galsworthy, To Let);  She had a look of spring and was smiling as if smth. pleasant had just, happened to her(Galsworthy; The End of the Chapter);
    Human is Stone: ...his whole face was colourless rock: his eves was both spark and flint (Bronte, Jane Eire);  Two shining arrogant eyes had established dominance over his face (Dreiser, Genny  Gerhardt);
     Hum an is Element o f Nature:  ...silent but unashamed, with flaming cheeks and angry eyes, the girl watched(Galsworthy, The  Man o f Property);  ...she was like a well of sweet water met with in a desert(Galsworthy; The End of the Chapter).
      It is difficult to overestimate the role o f conceptual metaphors in the fictional text. One o f the most frequently used image-schemes here is a container metaphor “Man is Nature”. 
Practically, almost all fictional text employ this type of metaphor in various forms and degrees of implicitness. An interesting illustration o f this type of metaphor is the story “Odour of Chrysanthemums” by D.H. Lawrence. 
     The heroine of the story, Elizabeth, a young woman, who was accustomed to a dull, dreary routine o f waiting for her drunk and abusive husband. The story relates her thoughts and reflections, the feelings o f regret, disappointment, anger and despair. The description o f nature given in the story is in full conformity with the heroine’s psychological state. The key-word o f the story is the word “dark” which is repeatedly used (14 times) both in the description o f nature and surroundings o f the heroine: Darkness was settling over the spaces o f the railway and trucks;
        The garden and fields beyond the brook were closed in uncertain darkness; The night was very dark; Indoors the fire was sinking and the room was dark red. The woman put her saucepan on the hob, and set a batter pudding near the mouth of the oven. Then she stood unmoving; She went out. As she dropped piece after piece o f coal on the red fire, the shadows fell on the walls, till the room was almost in total darkness. Soon the room was busy in the darkness with the crisp sound of crunching;
        She set down the candle and looked round. The candle-light glittered on the lustre-glasses, on the two vases that held some o f the pink chrysanthemums, and on the dark mahogany ;And her soul died in her for fear: she knew she had never seen him, he had never seen her, they had met in the dark and had fought in the dark, not knowing whom they met nor whom they fought .
The deliberate repetition o f the word “dark” creates an  analogy between two conceptual domains Nature and Man,  engendering metaphorical senses of the lexeme “dark” (cheerless, sad, sullen, bitterly, sharp, dangerous, nasty, dreary, violent, trapped, irritably, unbearable, angrily, etc.)attributed to Elizabeth’s inner psychological state o f disappointment and despair, dissatisfaction and isolation, irritation and annoyance, anxiety and fear. It should be noted that the description of her psychological state is supported by the descriptions o f the natural environment the heroine’s lived in:
     At the edge o f the ribbed level o f sidings squat a low cottage, three steps down from the cinder track. A large bony vine clutched at the house, as if to claw down the tiled roof. Round the bricked yard grew a few wintry primroses. Beyond, the long garden sloped down to a bush-covered brook course. There were some twiggy apple trees, winter-crack trees, and ragged cabbages.
     Beside the path hung dishevelled pink chrysanthemums, like pink cloths hung on bushes.
The extract evokes the atmosphere of depression, impoverished existence and coldness. This is achieved by the abundant use of conceptual metaphors (floristic type), which projects the concrete conceptual domain of “withering nature” on a more abstract one, that o f the “inner psychological state” of the personage.
       In the story under analysis the most conspicuous floristic type of metaphor is “Elizabeth is Chrysanthemum”. As is known, chrysanthemum is a late blooming, a beautiful flower of various colours. Besides its denotative meaning, Chrysanthemum has many a symbolic meaning associated with mythological legends.
       It can symbolize either positive notions: optimism and joy, perfection and happiness, a long and healthy life (mainly in Eastern culture) or negative ones: grief and death (mainly in European culture). Thus, in some countries, for example France, Italy, Spain, Poland, Hungary, Croatia, chrysanthemums are symbols of “death”. These knowledge structures are of considerable importance for text interpretation since they help to decode conceptual information implied in the story.
      In the context of the analyzed story “chrysanthemums” acquire additional and connotative meanings of a negative character. Moreover, this word has crucial relevance to the conceptual sense of the whole text. Suffice it to mention that it is repeated throughout the story 9 times and used in the title, too. The descriptions o f chrysanthemums given in the story don’t arouse positive feelings:
       Beside the path hung dishevelled pink chrysanthemums.
      like pink cloths hung on bushes
   ...tore at the rapped wisps of chrysanthemums and dropped the petals in handfuls along the path
...broke off a twig with three or four wan flowers and held them against her face. When mother and son reached the yard her hand hesitated, and instead of laying the flower aside she pushed it in her apron-band.
      The view o f shabby flowers made Elizabeth feel nasty, pitiful; she was plagued by unhappy presentiments and associations. Quite different is her daughter’s perception o f chrysanthemums:  Oh, mother!; You’ve got a flower in your apron!; Let me smell!; Oh, mother—don t take them out!; Don ’t they smell beautiful!. 
      The following examples are illustrative of Elizabeth’s feelings associated with these flowers: Her mother gave a short laugh.
‘‘No,” she said, ‘‘not to me. It was chrysanthemums when I married him, and chrysanthemums when you were born, and the first time they ever brought him home drunk, he ’d got brown chrysanthemums in his button-hole. ”
      She set down the candle and looked round. The candle­light glittered on the lustre-glasses, on the two vases that held some of the pink chrysanthemums, and on the dark mahogany.
There was a cold, deathly smell of chrysanthemums in the room. Elizabeth stood looking at the flowers. She turned away... One o f the men had knocked o ff a vase of chrysanthemums... Elizabeth did not look at her husband. As soon as she could get in the room, she went and picked up the broken vase and the flowers.
      The image of chrysanthemums in the context o f the story marks Elizabeth’s most significant life events either of a positive (her marriage, the birth of daughter), or negative character (drunk husband, his death). The breaking of a vase with chrysanthemums at the end of the story symbolizes both the death of her husband and the death of her soul:  She was driven away; trembled and shuddered; an anguish came over her; her soul died in her for fear; felt the utter isolation of the human soul; her life was gone like this, etc.
     So, the conceptual metaphor “Elizabeth is Chrysanthemum” conveys the multitude of associations and connotations: “chrysanthemum” (disheveled, wan, ragged) is a) a symbol Elizabeth’s routine and unhappy life; b) a symbol of her inner psychological state (disappointment, dissatisfaction, irritation, annoyance, despair, regret); c) a symbol of her husband’s physical death and her spiritual death.
The results of this section can be summarized up in the following conclusions:
cognitive metaphor is one of the fundamental processes of human cognition, a specific way of conceptualizing reality based on the mental process of analogy and knowledge transfer from one conceptual field into another;
container metaphor is one of the most omnipresent types of conceptual metaphor which being of a prototype character, gives grounds for modeling one of the main principles of human cognition on the basis o f body-based experience, human-being relationships, orientation in time and space, etc.
container metaphor built on the relationships of Nature and Man, is one of the key metaphors employed in the fictional text.
"""),),

        )
    );
  }}